export const colorMap = {
    // Màu cơ bản
    Red: "Đỏ",
    Blue: "Xanh dương",
    Green: "Xanh lá",
    Yellow: "Vàng",
    Black: "Đen",
    White: "Trắng",
    Gray: "Xám",
    Pink: "Hồng",
    
    // Các màu thời trang phổ biến
    Navy: "Xanh đậm",
    Beige: "Be",
    Brown: "Nâu",
    Cream: "Kem",
    Burgundy: "Đỏ đô",
    Khaki: "Kaki",
    Olive: "Xanh ô liu",
    Purple: "Tím",
    Orange: "Cam",
    Gold: "Vàng đồng",
    Silver: "Bạc",
    Turquoise: "Ngọc lam",
    Mint: "Bạc hà",
    Coral: "San hô",
    
    // Các tông màu pastel
    "Light Blue": "Xanh nhạt",
    "Light Pink": "Hồng nhạt",
    "Light Green": "Xanh lá nhạt",
    "Light Yellow": "Vàng nhạt",
    
    // Các màu đậm
    "Dark Blue": "Xanh đậm",
    "Dark Green": "Xanh lá đậm",
    "Dark Red": "Đỏ đậm",
    "Dark Purple": "Tím đậm",
    
    // Các màu khác
    "Sky Blue": "Xanh trời",
    "Royal Blue": "Xanh hoàng gia",
    Indigo: "Chàm",
    Violet: "Tím nhạt",
    Lavender: "Oải hương",
    Teal: "Xanh lục lam",
    Maroon: "Đỏ sẫm",
    "Hot Pink": "Hồng rực",
    Magenta: "Hồng tím",
    Ivory: "Ngà",
    "Off-White": "Trắng ngà",
    Charcoal: "Than",
    Taupe: "Nâu xám",
    "Light Gray": "Xám nhạt",
    "Dark Gray": "Xám đậm",
};

export const colorHexMap = {
    Red: "#FF0000",
    Blue: "#0000FF",
    Green: "#008000",
    Yellow: "#FFFF00",
    Black: "#000000",
    White: "#FFFFFF",
    Gray: "#808080",
    Pink: "#FFC0CB",
    Navy: "#000080",
    Beige: "#F5F5DC",
    Brown: "#A52A2A",
    Cream: "#FFFDD0",
    Burgundy: "#800020",
    Khaki: "#F0E68C",
    Olive: "#808000",
    Purple: "#800080",
    Orange: "#FFA500",
    Gold: "#FFD700",
    Silver: "#C0C0C0",
    Turquoise: "#40E0D0",
    Mint: "#98FB98",
    Coral: "#FF7F50",
    "Light Blue": "#ADD8E6",
    "Light Pink": "#FFB6C1",
    "Light Green": "#90EE90",
    "Light Yellow": "#FFFFE0",
    "Dark Blue": "#00008B",
    "Dark Green": "#006400",
    "Dark Red": "#8B0000",
    "Dark Purple": "#4B0082",
    "Sky Blue": "#87CEEB",
    "Royal Blue": "#4169E1",
    Indigo: "#4B0082",
    Violet: "#8A2BE2",
    Lavender: "#E6E6FA",
    Teal: "#008080",
    Maroon: "#800000",
    "Hot Pink": "#FF69B4",
    Magenta: "#FF00FF",
    Ivory: "#FFFFF0",
    "Off-White": "#F8F8FF",
    Charcoal: "#36454F",
    Taupe: "#483C32",
    "Light Gray": "#D3D3D3",
    "Dark Gray": "#A9A9A9",
    "Xanh lá đậm": "#006400",
    "Xanh lục lam": "#008080",
    "Đỏ sẫm": "#8B0000",
    "Tím đậm": "#4B0082",
    "Hồng tím": "#FF00FF",
    "Xanh trời": "#87CEEB",
    "Oải hương": "#E6E6FA",
    "Hồng rực": "#FF69B4",
    "Chàm": "#4B0082",
    "Than": "#36454F",
    "Xanh hoàng gia": "#4169E1",
    "Ngà": "#FFFFF0",
    "Nâu xám": "#483C32",
    "Xanh nhạt": "#ADD8E6",
    "Hồng nhạt": "#FFB6C1",
    "Xanh lá nhạt": "#90EE90",
    "Vàng nhạt": "#FFFFE0",
    "Xám nhạt": "#D3D3D3",
    "Xám đậm": "#A9A9A9",
    "Đỏ đô": "#800020",
    "Kaki": "#F0E68C",
    "Xanh ô liu": "#808000",
    "Tím": "#800080",
    "Cam": "#FFA500",
    "Vàng đồng": "#FFD700",
    "Bạc": "#C0C0C0",
    "Ngọc lam": "#40E0D0",
    "Bạc hà": "#98FB98",
    "San hô": "#FF7F50",
};

export const getVietnameseColor = (englishColor) => {
    if (colorMap[englishColor]) {
        return colorMap[englishColor];
    }
    return englishColor;
};
export default colorMap;